/*
    各种操作符测试
*/
import 'java.lang.System' as system;
var a = 1;
var b = 2;
system.out.println("a = " + a + ", b = " + b);
var c = a + b;
system.out.println("a + b = " + c);
c = a - b;
system.out.println("a - b = " + c);
c = a * b;
system.out.println("a * b = " + c);
c = a / b;
system.out.println("a / b = " + c);
c = a % b;
system.out.println("a % b = " + c);
c = a > b;
system.out.println("a > b = " + c);
c = a >= b;
system.out.println("a >= b = " + c);
c = a == b;
system.out.println("a == b = " + c);
c = a < b;
system.out.println("a < b = " + c);
c = a <= b;
system.out.println("a <= b = " + c);
c = a != b;
system.out.println("a != b = " + c);